// const puzzleInput: string[] = [
//   "XXXXXXX",
//   "XMXMXMX",
//   "XXAAAXX",
//   "XMASAMX",
//   "XXAAAXX",
//   "XMXMXMX",
//   "XXXXXXX",
// ];

const puzzleInput: string[] = [
  "SMMMXMASMSSSMSMMSAMXSSMMSXMMAMXMXXXSMMSXXAMAASMSSMSSSMSASMMMXSXSMMSSSMSMXSXMAMAAXAXMMAMXMMMMSXSASMXMASAAMAMXMXAMAXMAXAXSAMSMXMMMAMAASASXMAMX",
  "SAMSAMXSAAAAXMASXXMAXAAAXMSMMMSSMMMXAAMMSMASMMMAMAAAAASASAXSAMXSXMAAMAAMAMASAMXSMMMSMAMASAMXAAAAMXAMXMAMSAMAMMAMXMXMASMAXMXAAMASAMMSMASAMSSM",
  "SAMMMMAMMMSMMMSMMMMMSSMMXXSAAMAAAMMXMMSAMMAMAAMASMXSMMMAMAXMASAXAMMSMXAMMMAMAMAAAAAMAASMSXSMMSMSMSSMMXAMSASXSAAMXSSXMXAMXSMSMSASAXSAMXMAMAAX",
  "MXMAXMXSAXAMXMMAMAAMXMASMASMMMSSMMSASAMASMASXMMAXAMXMXMAMXMAAMMSSMAXMMSASMSMAMXSSMSSSMSXSXXXAAXAMAAAXSAXSAMASMSXSMMXSMSXASAMXMMSMMSASASAMSSM",
  "SAXMMXAMMSMSAMXAMMASASAMMAMAXAAMMMSASASXMMMSASMXSASXXXXASASMXSASAMXSXXMAXAXSMSXMAMAAAAXXMASMSSSMMXSMMSMMMAMXMXMMAAAASAXMXSXMAMMXMAXAMXMAXXAA",
  "SMSSSMMSXAXMASXSMSASXSSXMSMXMMMMAAMMMAMMAMXSAMAXMASXMSSMSASAAMMSXMSXMXMSMSMAMSXSAMMMMMMAMXSXXAMXAAMAMSASMSAMXASMSMMXSAMMXMMSXSMSSSMSMASMMSSM",
  "XAAMASAAMMSSMMAAAMAMAXAXMAMXMSMSMSSXMAMMMXMMMMMMMAMAMAAXMAMXMXMXAXMAXSAMAAXSMSASMSSSXSXMAAXMMAMSMMMAMSAMAMXXMXXAMMMXMMMXAMAMXAAAAAAAMXMAAAXM",
  "MMMSAMXSAMAAAMMMMMSMMMMSMASAAAAAXAAXMSSSMAAAXAMAMAXAXXAXMXMXXAMSAMSAMXAMSMMXAMAMXMXAASMMMSSMMMMSASXSMMAMXMAMSSMMMASAMMSSMSAMSMMMSMSMXSSMMMSS",
  "XSAMXSAAMMSSMMXMAAAAAXXXMAMMSMSSSMMXAAAASASMSXSSSXSMSSMMMSMMSXMAMXASASMMXXAMXMXMAXMMMMAAAXAMASMSAMAAAXAXMMMMAAXMSASAXSAAAMAXAMXMAMXMAXAXMSAX",
  "AMAMSMMMMMMAXSAMMSSSMMMMMMSAAXAAAXXSMMSMSMAMMXXMMMAMAXMASAAMAMAASMAMXMAAXMSSXMXSXSMMXSSMMSAMXSXMAMSSMMXAXAAMMSMXMAMAMMMMSXSMSAMSMSAMMSAMXMMS",
  "MXSSMAAXSSSSMMSSMXMAXAAAAAMMMMXSAMASAXXXXXMAMMMAXSAMSASMSSSMMSMMMMAMASMMMAXMAMASAAAAXXAMAXMMMMXSXMAXAMXSXXXSAXXXMSMSMSXAMAMAXAXMXSASASXXAMXS",
  "MAMAMXMXAMAMAMXXMASAMSSMMSMXXMAMAXASMMMSMMSAAXSAXXXMXASAXAMXMAXSXSMSMSAMMMASXMASMSMMMSAMSSMSAAAAAMASXMAXSASMMXASMXAAASMSMAMASMMAASXMASXMAMXM",
  "MAMAMXSAMMMMSMXAXAMAMMXMAAMSASMSMMMXMAAAAASMSAMXSXMXMAMAMMMSAMXMASAAXXMXASMMXMASMMAAAMAMXAASMSMSMMASAMASMMSAMSAMAMSMMMAAMMMXXMAMXXAMMMMASMSM",
  "SMSXSASAXXXMAMSSMSSXMXAMXSMSAXMAMAMMMSSMSMMMXXMASAMSMXMXMAAMAXMSAMMMMSMSMSAMXMASASMMSSSMSMMMMAMXAMXSXXMAXXXAMSAMXMXSAMXMSXMSMSMSSMMMSAAXXAAS",
  "AAAAMASXMXMMAMXXAAAXSXMSXMAMXMSASAXMAMXXXXMASASASAMXMAXAMXMSSMAMASXXXAAAASAMXMAMAMAMXMXMASAAMMXSAMXMAMXMXMMSMSMMMSAMXXMAMXXAAAAAXAAASMSXMSMS",
  "SMMSMMMMMMSXMASASMMMSAAMMSAXXXSASASMASMMSAMXSAMASMMXXSSMXXMAXAMSAMMSSMSMXSAMXMXSSXXMXMASMMXMSMASAMXSMSAMMSXXAXAAAMASASAAXMSXMMSMSMMXSAMXAAAM",
  "XAXMAXAAAAMAXAMXXAXASMMMAXMMSAMXMXAXXSAASAMAMXMAMAMAMMAMSSMMSSXMMXSAAXXMAXAMXMMMMAMSXSASXSSXAMASAMXAXSASAMMMMMSMMSAMASXMAMMSMAXXAXSMMAMMMMSM",
  "SMMSXXSSSXSMMSSMSXMAXASMXMAAMASASMXMXMMMSAMXXXMAXAMAXXAMXXAAAMXMAMMSSMMXSMSSSSXAMMMAAMASAAAMAMASAMXMASAMXMAAAMAMAXMMAMAXXAAAMXMMMXSASXXAAAAM",
  "MXXMXAMAMMAXAAAAXMMMSMMASXMMSAMASAASXMSASMASXXSSSMSSXSAMMMMMXSAXMAXXMAXAAMXAAXSAMXMMXMXMMMSMMMXMAXAXMMXMASMSMSASXXMMASMSSMSMXSXXSAXMMMMXMSSM",
  "MMSSMMMAMSAMXSMMMMAAAMMMMASAMXSMMXMSAAXAXMASMAMXAAAAXSAMXAAAXSAXMXMASAMSSMMMMMMSAXXSXXSASAMAXXXSMSSSXXXXASXMMXAXXAMSXSXAMAXAASMMMXSXMASMMAAX",
  "SAXMAXMMMMXMMXXAAMMMXMAXXAMASAAMXXSMMMMAMMMSMAMASMMSMMAMSSMSAMXMSSSMMAXAAASAMXMAXSMSAASAMAMSMSMSAAAMMMSMXXAMASMXSAMXMMMMMAMMMMAXAXSASASMMSSM",
  "MXXMXMMMSMSMSASXSMSXSSSSMASAMMXSAMMAMAMMMSAMXMMAXXXXMXSMMAXAAXXAXAAMSXMMMMXAMAAMXSAMMMMAMSMMMAAXMMMXMASMSSSMAXSAMXSAAXMXMASXSSMMXXSAMMSAMMAM",
  "SMSMMASAAMXAMAMAMASAAAAMXAMAASAXMAXAMAMSAMAXASMASXXMSAMAXMMSMMMMMSMMMMMSSSMSSSSXSMMMAAXXAAXXAMSMXASAMXSAAAAMASMMMAMXXMMSAMXAMAMXXMMMMASAMSAM",
  "AMAASAMXSXMSMAMSMAMMMMMMMMSXMMXSXSSXSASMMMSMAXXAMMASMASXMMXXSXAAMAXAAMMAMAAAAXMXXAASMSMXSXASXMMASASASAMMMSMMMXAXMASMSMASAMMSMMMXXSSMMXMMMMSM",
  "MMSXMASAXXAMSXSXMSSSXMXSAMXMSAMXAMAAMXXAXAMMMMMAAMSXSXMMAMXMASMMSASXMSMAMMMMSMSAXSMSAMXAXXXXAXXXMASAMMSMAMAMMSMMMXAAAXAMAXSAAASMMMAMSSMSAAAX",
  "XXMAXAMAMMSMMMXAXAAMXMAXMXAAMXSMMMSMMXSSMMSAAAXSAMAAXXXSAMMAMXXAMMMXAXXSXSAMXAMAXMAMAMMMMMSSMMXXMXMASAXMASASMAAAXMMSMMASXXSXSMXAAXAMSMASMXMS",
  "MMSSMMMSMMXAMASMMMSMAMAMASXSMAXASAXXSAXMAMSXMXXAMXMMMSMSASASXXAXXSAMXMXMXMASMMMXAMAMAXAAAMAAAXMMSXMAMAXSASASXSSMMAXXXXAMMMMXXMSSMSSSXMXMMSMM",
  "MAAXAXAMMXMAMAXSAXMXAXSAMMXAMXSXMASAMMSSXMXAMXMAMSMXAAAMASAMXMASXMASMXAMASXMAXSMMSASXSMMMMSSMMAAAAMXSXMAASAMXMAMMSMMMMMMAAMSMMMAAAXMASXSAAAX",
  "MMSSSMMSASAAMXSXSAMXMAMAXSSSMAAMMAMXMXAAMSSMMASAMXAXSMSMAMAMSAAMAXSAXMASAMASMMSAASASMMMSSMXAAXMASXMMMMSMMMXMXXXMXXAAAAASMSMAAASMMMSXAAAMXSMM",
  "XXAXAAAMASMMMXMAMXMAXAXAMXAAMXSSMXSAMMMSMAAASMSMSMMMAAAMAMXMMMSSSMMAMMAMAMAMMAMMMSSMAAAAAASXMMSXMASXMAAAAXMMMMSMMMSSSMXAAAXXSMSXSXXMXMXMAMAM",
  "SMMMMSMMMMXAXXMAMASXSSMSAMSMMMXXMASXXAAAMMSMMASXAAASMSMSSSXAXAXAMXSASMSXSMSSMSSSXSASXMMSSMMMAXMASAAAMSSXMXXSAMAAAXMAXXSMSAMXAMXMXMASMXMMASAM",
  "MAASXMXSMMSSSSMXMXMXAXAXSMMXXAXMMASMSSSXSXAMAMXMXXXXAMAMASMSMXSAMXMASXMAAMAAMMAMXSMMMSAXMAXXMXMASMSXMAXAMSMSASMSMSMMXMXAXASAMXXXMAMAAASMASAM",
  "MSMSASAXAMAAAMMXSMMMSMXMMSXMAMMXSAMXAAAASMSMSXAMMMSSSMMXAXSXAXMXMAMXMAMSMMSSMMAMMMXMAMMSMSSSXAMXXAAMMASXMAAXAMAXMSAASAMXMAXXXMXMXSMMSMSXMMXM",
  "MAXXMMMSSMMMMMMAAAXSXSXMAAMMSMAXMASMMXMXMAMAXMXSAAAAXAXMSSSMMMMSMSSXMXMAMAMAXSMMAAAMAXMAMXAMSSMSMXMXSASMSXSMAMAMMSXMMXXMMMMSMMAXAAAAMMXAMSMS",
  "SSSMAAXMASXXMAMSSMMMAMMMAMSAAMSSSMMAXSXMMAMMMMAMMMMMMMXXMAMXXAXAAXXMMAMASAAMMAMXXXXSASXMMMMMAMMXAAXMMMSAMAAXXMXSXMMMXMXMAMAAASAMSSMMSMSMMAAS",
  "SAAMSMSMMMMMMAXMAMAMAMAAMSMMMSAMXASXMASAMASAAXAMXXXXSSMSMAMMSSSMSMAMXMXASASXSMMXSAMSAMXXAAAMMSMSAMSXSAMAMSMSSMASAAAXASMMAMSMXMSMMAAAXAAMMMMM",
  "MXAMXXMAAAAAXMMMAMXSMSSSMAMXXMASXXMAMAASAMXXASXSSMXSAAASMXSMAAMXXXMMASMMSAMAAXAAMAMXAMASMSSSXAAXXAXAMASXXXASAXAMXMMMXMAXSMMXSAXSSSMMSSXSSSSS",
  "MSXMAMXMSMSXSSSSMMXXXAXMMAMXMSXMMSAMXSAMXMASXSXMXAXAMMSMMMSMXXSAMAMSASAAMAMSMMMMSAMXSMAXXAXXMMMMASMXMMMMMMMMMMMSASXMSMSMXASAMXMAXAMMXMAAXXAA",
  "AAASMMMAMAAAXAMMASMSMMSSSXMMASAMXASXMXASAMXSXMASMSMMXXAAAAXXMMMASAMMASMMSAMAXASXSASAXMASMXMMXSXAMAAXMASXAMAAXAXSAXAXAAMASAMXMAMMSMMXAMMMMMMM",
  "MMXMAAXAXMMSMAMSAMAXAAAMXMASAMAXMAMSMSASXSAMMXXMAMAXSSSSMSSXAXMAMAXMXMAASMSMMXSAXAMASXXXMASXASAMXMSXSASXSSSSXSXMMSSSMMMAMXMASASXSXAMMMMAAMAM",
  "SSMSSMMXSMAXXXMMASMSMMMSAAMMASXMMSMMMAAMAMXSMXSSXSSMMXAXAXAMSSMMSMMSASXMSAAXSSMMMXSXSXSASASMXSASAXXMMASAMAMXAMXAMAAXAXSMMASXSXSXMAMSMASMMSAS",
  "MAAXXXMXXMAXMSSMMMAAXSASASMMMMMXXXAAMMMMXMAAMAAMAMXMXMMMSMMSAAXAAAXSAMXSMMMSXAAXMAMXMASAXSXMAMAMXMMXMAMXMAMMMMAMMMSMXMAASXMASAMMAMSAXXSAMSAM",
  "SMMMMASMMXSSMAMMAMMMXMASAXMAMAMXXMSMSXMXAMMAMMMMSMSXXXSAMXXMMSMSSSMMAMXAMXXSMMMMMASAMXMMMMSMXMSXSSMSSSSSXSAMXASMSSMMMSXXMAMAMXMAAXMAMXMAMMAM",
  "AAAASAAAMAMAMMXSAXAAAMXMXAMMXSSMMMXAMXXSXMXXXAAXMASAMXMASMMMXMAXXMASAMXMSSMMASXXSASXSAMXAAXMAAMMMAAXAAAAXXXXXXXSXAAAASXSMSAMXSSMXSMAMXSAMMAM",
  "XMMMMAMXMXSAMMASMSMXMMASMSASAMAASASASAMXAMSMSSSSMAMMMXMAAAAXAMMMASASAMXXAAAAAMMXMASXXMSSMXSMMSMASMMMMMMMMSMMSSXAMSMMXSAMAAAXAMASAMMAMXMAMSMS",
  "SASXSSMMXXMAMMAMAXMASMMSAXAMXXSMMAMXMMAMXMAAXAMXMXSXMASXSXMMMSMSXMASXMXMSSMMSSXXMMMMSXMXXASAMAMXMMAXXXAAAAASAMMSMXXXMMAMMMSAAXAMMXSMSSSSMSAA",
  "XAMAAXMXASXMMMMSMMSASAAMXMSMSXMXMSMSMSMXMMSMMASXSAMXSMMAMXAAAAAMXMAMASXXAMXXMMMXXAAXMAXXMASASASXSSXSXSXSMSMMAMAAXXXMASAMAAXMXMXSXXMAMMAMAMXM",
  "MSMSMMSAMXAXMXXAXXMMSMMSAMXAASMAMAAMASXAMAMASAMMMAXXAAMSMMXSXMXMAMASXMSMSSMXXAXMSMXSSMMMMASAMXMAASAMASAAAMMSSMSSSSXXAXAMMAMMXMSMMMMAMMMMSMXM",
  "AXAXMAXMXSMMSSSSSSMXSXXMASMXMXMAXMXMAMXMMASXMAXASXMSMMMXAMAMAMMSASAMAAAMMAMSSMMXASXMAMXXSASASXMSMMSMAMMMMMAAAXMAXMMMMSSMMSXXAXXXAASAMSAAXMAM",
  "SMAMMMSXAAASXAAMAMXAMAMSMMMMSASMXSAMXSSMAASXSXSXSSXXAAASXMASAMAAAMASMXMMMAMXASXSASMSAMMMMASXMAMMAXAMXXXXAMMMSSMSMMAMAAMSAAXSXMMMSMSAAXMAMSAX",
  "MMXMAXXMMSMMMAMMXMMMXAAAMAMSMAAAASXSAAXAMXXAXAAMMMMSAMXSAMXMAMXSMSMMXSXSMMMSMMXMMMAMAMSAMAMASAMXXMMXSSMMSSMAAMXMASMSMMSMMSMSAAXAMXMMMXXXMSAS",
  "SAXSMSMSAMAAXSXMXSXMSMXXSASXMSMMXMXMASMMMSMMMSMXXAAXAMXXMASXXMXMMXMAASXSASASASXSSSMSSMXMMMSMSXMXAMXAAAAMAXMMSSSMAMAAXMAXMMASMMMSSSXAMMMAMMSA",
  "MAMAAAAMMSSMSASAMMAMAMSMXXAMXAMXSMXXAXAAAXAXAMXSXMMSAMMXMAXXMSMXXAMMMSASMMASAAAAAAAAXAAXMXSAMASXMSMMSSMMMSXMAAXMAXXMMSASMMAMXXAXMASMXAAAXMXM",
  "MSSMMMSMAAAMSAMXAMAMASAASMSSSMSAAAAMXSSMMSXMXSASAMAMMAMXMMSMAMAXMSSMXMAMXMXMMMMMMMMMSXAXSAMAMAMAAAXAAMXAAMASASXSMSMSAXMSAMXMXMSSMMXXSMMXXSAM",
  "XMAMXMXMMXMMMAMASXXXXXMXMAAXXAMXMXXSMMXXXMASAMASMMASXSSMXMXAAMMMXAAAAMAMXMASMXXXXXXXMXMSMMSAMXSMMMSMXSXMMSAMMMAAAXAASXASMMASXMMAMXAAASMSXSAS",
  "MSAMSXSXSAMSSSMAMMMSSMSAMMMSSSMAXMXMASAXMSMMMMMMASAMXAAXMSMSXSMSMSSMSXSAMXXMMMSMAMSXSAXAAMMAXAXXXXAMMSAAAMMMAMSMSMSMMXAMXMAAAXSAMXSMAAXMASAM",
  "AMAMXAMAMMSAAAMMSAAAAASMXSAMAAXAASMMMAMMMAXAMASXMMXMASMMAAAXXSAAAMAXAAXMASAAAAAAAMAAXMSSSMMASMXMASXMASAMMSXSXXMAXXXAMXXSAMXSAMMAMAXSSMAMXMMM",
  "SMSSMAMAMMMMSMMXSMSSMMMMAMAMSMMSSMASAXMMSAMMSASMXMAMMAMMSMSMAMXMXSMMMSMXSAMXMMSSXSMSMXMXAAMAXAASAMXMXSAMXAMMMMMMMMSAMXXXXMXMASMSMMMMMXXSAMXM",
  "MXMAMMXAMXAXAAMMMAXMXSAMXSXMASXXXXAMSSXAAMSMMMMAXMAXMAXMXMAMMMASMAXAMAMXAMXAMMMMXMAAAAMSXMMSXSMMSSXXXMASMMMAAAAAAXSASXSXSAMXMMAMXMAMAXMAMSAS",
  "SMSAMSSXXSASMSSMMAMMSSXSAMXSASMXMMMSMXMSSMAXASXSMMAXSSMMASASXMASASMXSAMXXSXXMAASAMSMSXXAAMMMAAXAMXASXSMXAASXSXSMSMSAMAAAAMXSSMAMXXMMMAMXMSAS",
  "SAMXSAMSAXASAAMXXAXXAXMMXSXMASAAAAMAMAAAAMXXXSAAXXAMXAMSASXSAMASXXAXSAMSMSAMSSSMMXAAXMASXSAMXMMXMMMMAAAXMMMAMAXXMMMMMMMMMMAMAMXSMXSASAXAMXXS",
  "MMMXMAMMSMAMMMSMSMSMMSAMASMMMMXSMMSAMSXXAMXMSMMMMMSSSMMMASASXMASXMXMMAMMAMAMMMXAXXMSMMMAAXXXMXXAXAMMSMMSMAMAMAMAXXAXAAXXSMXSMMMSAASMSASMSMXS",
  "MSXMMSMAAMXMAXAAASAAXXXMASXXSMAXAASAXXMAXAMXAAXMAXMAXXAMXMXMXMASMAMMMAMMSMMMXASMMXMAAXSMSMAMASXMSMSAMXAAXAMMMMSAMXMSXMMXASAAXAAMMMSXMAMXAMAM",
  "XAASAMMSMSSMXSSSMSSSXMXMASXAXMAXMMMSAMXXXAXSMSMMMMMAMSXSAMXSXMASASAAASXMXAXSMMMXMASAMMXAXMMAXSAAMXSAMMSSSMSXAAMMMSAXXSSMMXMXSMSSSXXMMSMSMMAS",
  "MMSMASMAXAAAAMMAAXXMASAMXSMMMMSXMMXMMSAMSSMAXMMAMSMMMSXXAMASASXSXMSSMMASMSMXAXAXMASASAMAMMXSASMMMASXMAMXMASMMMSAAMXMXXAAXMSAMXXMMMXXXAAAXSAX",
  "MMMMMMAMMXSMMSXMMSAMXSASAXASXAMAMAMMAMAMAAMMMSMAMAAAAMMXSSMMAMAXXXXMXSAMAMXSMMSSMAXAAMMXXXAMAXASMXSXMXSMMAMAAMMMMSAMXSSMMAMASMSASAXXXMSMMMSS",
  "XSXAAXXXMAXMMXASAMAMASAMMSAMMSSXMASMAMMMMSXSAMMMMXMMSXSAAAAMSMMMSSXMXMMMAMAAXAAMMAMSMMSXMMXSASXMXSMAMXAMMAMMXMASMSASAMAMMSSXMASAMSSXAXAXXAAM",
  "XASXMSXAMAXAXSMMASXMAMXMMMAXXAAASAXXAXMAMMAMASASMSSMMAMMSMMMMAAAXMSMSMASASMSMMSSMMMXAAMASAXSAMMSMMSAMXMMSMXSAMXMASAMXSAMXXXMMMMMMAMXXMASMMMS",
  "AMAMXMMMMMSMMSXSAMXMASAMXASMMMSMMASMMSMASMAMAMASAAXAMXMXXAMMSXMMMAAXAMASMSMAASXXXAAMXMSAMSMMXMAAAMMMMSAAXAASXMASMMSMASASMMASAXAAMXSAMMAMAXSX",
  "SMASAXAXAAAAXXMMAXXMAXASAMAAXAXXMXMAAXMXMMXMAMXMMMMMMMSMMMXAAAMSMXMSMMASXXMXSMMXSMSXMMMAMXXXAMSSSMAAAMMMXMMSASXSXAXMXMAAAMASXSSXXAMXXMASMMSM",
  "AMAMAMSMMSSSMSXSXMMMSXMMASXSMSSMMAXMMSAMXMXSSSSMMSAASAAXMAMMSSXAASXSAMXSAMXSAMMXMAXMAASMSMMMAMMAMXSMMSSMSAMXXMAXMASXASXSSMMSXMASMSMSASAMXAMX",
  "MMSSMAMAMAMAXMASXMAAXASXMMMMAMAASMXSAAASASMMMAAAASXSMXMSMXMXAMMMMAASMMXSMAXSAMSXSASMSMSAAAMSSMMAMAMAXAAMSAMXMXXXAMMAMXAMAAASMMAXMASAAMMSMSSX",
  "XXAAAAMAMMXSMMAMXMAXSAMAMXSMSMMMMAAMMSMSASXAMSMMMSXXMMSAMSSMMXXXAMXMXXAMXSXSAMXXMAMMAAMMMSXAAASMMXSAMMXAXAMXMXXSMMMAMMMMSMMXAMASAMXMXMXAXMAM",
  "SMXXMMXSMSAXMSAASMMMXXXXSMMAXAMXMMMMAAMMMMMXMAAAAMASAMSASAAXSASMXSAXAMXMAMXSAMXSMXMSMMMXXXMMSMMSMASXSASMSSMAMSMMASXXSXXAXAMSSMMAMXXXMSMMXMAS",
  "SAAMMMXAAMXSASMXSAMXMASMXAMAMSAMXAXMSXXAXMSMSSSMXSASAMSXMMSMSASAASMMSMSAASASAMXXAXXMMMXAMSMXAMXSMAMXAXXAAXMASAAAAMSAMXMASXMAMAMSAMXSAMASXMAS",
  "XAXSAASMMMAMAMMASAMXAXXSSSMASXXMSXSMMMSMXSAAAAXAMMMMXMXMXAXAMAMMXMAXAAMSAMMSAMXMXMXAXMMSMMMAAMAXMASAMMMMMSSXXXSMAMXMMAXMMAMXSAMXAMASMSAMAMAM",
  "MSMMXXXAAXMAMSMASXMMSMMAXASMXXAXSAMXAXAAMSMMMXMXSASMSMSMMSSSMAMXSSSMMXMMMAXSAMXAAAXMMSAMXAXMXMSSMASAAXAAAMAXMAMMMSASMSMSAAMMSMMSAMASXMASXMAS",
  "AMAXSXSXMMAMXSMMMMSXAAMMSMMMMSMMXMASMSMSMMMMXXSMSAMAAASMMAAXMASMAAMXSAAMASXSXMAXXSMXAMSSMMMSAXAAMAMMXMMSXSASMAXAAMAMAAAASXSXXMASAMAMASAMASXS",
  "SSMMAAASXMASXMASMAXMMXMXMXAAXAAAXMAMMAMXXXAMMMSAMXMXMMMASMMMSASXMXMASXSMAMMSASXSAAMMMSASAAASMMSXMSSMSMMXAMAMMSMMMSAMXMMMXXMXXMAXXMMSAMASAMMX",
  "XAAXMMMAXSAMMSAMASXMSXSAMXMXSMSAMXSMSASMSMSSMASXSMSASASXMAAAMXSAMXMXSAMMMMAMMAAAMMAAXMASMMMMMAXXMAAAAAASAMXMXMAMAMMMMMMXSMSMSMXSAMXMASXMASAX",
  "SSMMXAMXAMASXSASAXXMAAMAMMSMAXXXSMMASASAXXMAMMMAMAMASMAASMMMSASAMMXMMAMAXMSSSMMMXXMSMMXMXSSMXAXMMSSMSMMMAMXMASMMASAMAMXAXAAAAAASXMASAMXSMMMX",
  "XAXXSXSMXMASMSAMXXAMMMMAXAAMMMXAAAMAMAMMSASAMAMAMXMASXSXXMAMMASMMSAMMXMXMMMMMASXMXXMASASXMAAMMSAXAMAMAMSMMMMAXMSMSMSASMXSSMSMSMSASXSAMXXASXM",
  "SAMXXAXXXMAMXMXMMMMMASMMMSXXXMXSMXMXMXMAMMSMSXSASXMASAMAMXXXSAMAAXASMSMSAXMMSAMAMSXSAMAMXMAMMXAMMAXAMAXAMAXMXSMAAXXMAXXXMXMXMAMSAXAMAAAMXASA",
  "MAAAMAMMMMSMSAMXSAAMAMAAXAMXSAAMXXMASXMASMXMXXMASXXAMAMASMSAMASMMSAMXAASAMXXMMSSMAXMAMSMSXSSXXSMMMMASXSMSSSMASMSSSMSMSMMMAAAXXAMXMMSSMSXSASM",
  "SMSXSAAAAAAAXXMAMXSMMMSMMAXAAMMMMMSASASXMMAMMSMSMXMASXSXSAMXSMMMMAAAMMMMMMXSAAAXMMSSMMMAXAXMAMMAXAAMAMXXAMMMASAMXAXAAAAAXXSSXSMMMAXAAXAAMAMM",
  "MAMMMXXMMSSXSAMXSMMMSAMMSSMMMXMAAMMMSMMMMSMSAAMAMAMXMAMAMXMXXXAXXMXMASXAXMAXMMSMXXXAXSMXMXMSAMSSMMSXAMSMSSMSMMXMMMMMSMSMSAXAASAMMSMSSMMMMMMA",
  "MAMAMMSSMMAASXXAAXAAMMSMAXXXXMMMMSAMSMMSAAMMXXSMSMSSMMMAMAMXAMMMMXMMMMSXSMSMSXMASASMMMMMMXXSAXXXAXMMMMSMAAMSASMSMSAMXAAAMAMMMMAMXXAMXMASAMXX",
  "SASXSAXAAMMMMXMSMMMXXAAMMSMMMSXXXSMSMAAMMXSASMSXSXAAAXSXSASXMASASASAAXAMSAXAMXXXXAXXAXAAAAASMMASMMSXSASMMXMSAMAAXMSXMMMMMSXMASAMXMMMASXSASXS",
  "SMSAMXSSMMSMAXXAXAXSSSMSXAXAAMMMAXMXMMMSMMMASASAMMSMMMSASASMMSSMMAMSXMMXSAMXMMMMMMMSSSSMXXAXAMMMMAMAMASXAAMMXMMMSMMXMXSAMXXSMSXMASASMSASXMAS",
  "SXMXSAXAXSAMXXMASMMXAAASMMSMMXAXXMMAMMMMMXMAMMMMMAAAXXMAMMMXMAXMMSMMMMSAMXMAAAAAAAXXMAXMSXMXMMMAMAMXMAMMSXMAMXAXAAMXAASMSMXXXMAXMAXSASAMSMAM",
  "SAMSAXASMMSSMMSAXXAMMMMMAASXSMXSAAMMXAAAMXMASAAAMSSMMMMAMXSAMASMAMAXXMAMMASXSSSSSXXAMXMXAASASASXSMSMXSSXXXXSASMSMSMMMXSXAMAMMSXMMSMMMMAMAMAS",
  "SAMXMSMMSXAXXAMXSAMMAAMMMMSASAASXMMXSMSSSXSAMXSXXAXMAXMAXXSAXAAXAMXSASXMSMSXMAMXAASXMSSMMMSAMASMSAAMSMMMSMMXAXAXXMAXSXMMMSMAMAMXAAMAMXSMMSAS",
  "SSMAXXAAMMMSMMSAMMSSSSSSXXMAMMMMSXSASAAAAAAAMXXMXMASMSSSSMSAMXMSXSMAAAAASXMMMMMMMMMAAXMAXAMMMAMAMMMMAAAAAAAMMMMMSSSMMAMAMAXXAXSMSSSMSAXAXMAS",
  "SASXMMMMMAAMAAXAAXMAAXMASAMMMXAAXXMAMMMMMMMXMSAMMSAMXAAXXAXXXAXMAMAMSMMMMAMSMAAMASMMSMSMMMAMMXMMMMXSSSMMXXMXSAMAMAMMSAMXSASXMXXAMAAAMAMMMMAM",
  "SAMXSAXSSMMSMMSAMXMMMMSMAMMAXSMMSAMAMASAXAXMASAMASAMMMMMMSMMSAMMAMSXXASXSAMAMSXSAMMAMXXXAXSAMAXAASMMAAAMSSSMSXSAMAMXXMSMMASMXMASXSMMMXMSMMMS",
  "MAMAMMMXASAAXASXSMXMMAMXASMSMSAAMXMASXSMXMXAXSAMXSAASASAXMAMXMASASXMXXMASASXXXMMXMMAMAASMMXAXMMSXSAMSMMMAAXAXMXXSMSAXSAMMAMAXMAMMMAXSAMAAAAX",
  "SMMSSMXSAMSSMXSASXAXMASXMAAXAMMMSASXSAMAASXSXSMMXMMMSASASMMXAMMSMSAMSAMXMAMMAMXASXSASMMAMASXMMAMXSAMAXMMMMMMMSMAAAMMMSASMAMMXMASASXMMMSXMMMS",
  "SXAXAAAMAMAXMMMAMSAMSMSXMMMMXMMXMASXMXMMMSAMAMXMAAAXMXMMXAMSXMASMSAMXXMAMXXAMAMXMASAXXSAMMMXXMAXASXMMMMAMAAXAAMXMSMMASAMXMASMSXSXSAMXAAMXSMM",
  "XMAMMMMSSMXSMAMAMASXAXSXSASMSSMASMMMXMMXMMMMAMASXSMSMMXMSAMXMMMSXMMMSSSMSSMAMSSSMAMAMXSXSAMXXMMSXMMSXASAXSSMSSMSAAXMAMMMAAMAAMMMXSMMMMMXAAAM",
  "SMSMXXMAMXMAXASASMASMXXASASMAASAMAAXMAXASAMSXSASAMASAAAMSASXMAAMMXMMAXAXAXMAMXAAMMMMSASMSAMMASAMXAXXMMMXMXAMXAAMSMSSXSASXSXSXMAMXMXAAXASXSMM",
  "AAAMXXMASXSAMXSAMXMXXAMMMMMMSXMXSMMSAMSMMAMMAMXSMMAMMSXXSXMASMXSAASMMMSMMSMAXMSMMXAXMAXASAASAMASXXMMSSMMXMAMMMMMMXXAAMAMAAXAASXSASXSMSASXAXM",
  "MSMMAXMAXMMSAMXMXAXAMMXSAAXXMMXAXXAMAMSXSSMMXSMMXMMMXXMASASAMAAMXMXAMAAAXAXASXXMXSXSMSMAMXMMASAMXMXMAAAMASMXSASAMMMMMMAMXMMMMMAMAMAAAMAMMMMM",
  "MAMSMMMMSAAMSSMMMSXMXSASAMXAAMMAMMXSASXAXMASAXMAMMMAXXMAMMMMMMMMMSMSMSMSMMMSXXAMMMMXAAMXMAMXMMASXAAMMSMMAAXAXASASAAXASMXXXMXSMMMSMMMSMMMAAAX",
  "XAMAAMAASMMXAXAMXMAAAMXMASMXAMMSMAXSMSXMASXMASMSXSAMSMMASXMSAXASASAMXMXAAMSXXSSMAAMMMMXAMMSAXSXMASXSAXAMXSMMXXSAMXSSMMSMMAMAMASAXXSMMAXSXMMM",
  "SSSSSMSASMXMMSSMASMMMSASAMMXSMAAMSMXXSAMAXAXXXAXMAXSAAMAXAAMAMMMAMAMASXSMMAMXMASMSSMSSSSSMSXXXMXMAAMMMAAMMAMSMMAMAMAAAAMXAMAXMMAXXMAMXMAASMS",
  "AAXAXAMMMMSAMAAMMMXMAMMMAXMAMMSMSXMSMSMSXSMMSMMMMSMSMSMSSMMMSMSXXMAMSMAXSMMMASMMSMAAAAXMAMXXSMMSSMMAXSSMMMAMAASXMMSSMMSMSASASMMSMSMAMAMXAXAA",
  "MSMMMXMAAMSAMSSMSAAMSSXXMAMXSAMXMAAXAMASAMXASASAAAASAXAXXAMAAAXMASXSMMSMMXXXXSXXASMMMXMSAMXXAAAAAAXMAXMASMSSXXMSMXXAXXAASXMAXMAMAMMAMXMSMMSM",
  "MXAXAMSMSMSXMXMAXSMXAAXMXMXXMAMMSMMSSMAMAMMASAMMSMSMAMXMSMMSMSAMXAXAMAAAMXSAASXSMSXMXSMXMSSXSMMSXMMMXXMAMSAMXMMXSASMMMMXMAMMSMAMAMXSAMXMXAMS",
  "MSXMMMXAMAMSMMMMMAMXMSXSASMMMMMAXAAAMMSMMMSAMXXAXMXMAMMMAXAXXMASMSSMMSMSMAAMAMASXMASAXXAMAXAXAMXMMMMMSMXSMSMSSMASMMAAXSASAMAAXASXSAXMSXXMASA",
  "XXSAXMMMMAMAXAXXXAXXXMASASAAAAMSMMMSXAXSAMXXMXMMMAMSASASXSMMXSAMXAAXAMXXMMMXAMAMASAMASXSMASXSASXSAAAAXMMXAMMMAMXXXSMMMXASMSXMSMSAMASXMAAMSMM",
  "AASXMXAXSSSMSMSAMXSXAMXMXMMSXSXXMSXMMMSAMXSXAXMAMAMSXSMXAAASAMMSMSMMMSXMASASXXSSXMASMMMMXXSXMAMASMSMSXMAMSMASASMSMAASMMXMMSXXAAMAMAMAXMAXAAX",
  "MMMAXSSMXMAXSASMAAMMSMMMXMAMXMASXSXMAMAAASXSMMMASAXXAMAMSMMMASAXXXXXMAMSAMXMXSAMMSAMASMMSMMMMAMXMAMXMMMSAASXSASAAAMMSAXXAAXSXMSMXMASXSMSSSSM",
  "XAMSMMAAXSMMMAXXSXAAAAAMXMASAMAMAMAMSXXSMSAXSASASMMMSMAAXAXSXMMSMMAXXAAMASXSXAAMAMASAMAXXAAASXSXMXMMMAMXSXSMMAMMMXXXSAMSMMXXXSAMXSXMXXAAAXXX",
  "SXMAAMAMMSXXMAMXMMMMSMMXMMASAMASXSAMASMAMMMMAXMXMAXAAMMMSSMXAAAAAAXMMMSSMMMAXSSMXSXMASMMMSMXMASXMASAMAMAMXXAMXMASXMAXAAXAMXSXSASASASXMSMSMSA",
  "XMSMSMASAXMXMAXAAASXMMSAXMASXMMSXMAXAMXAMAASMSSMSSMSXXXAAXASMMSSSMSAXAAAASAMAMAMASASAAAXAAMAMAMAXAMMXXSMXASMMMSASAMAXSXSMMMMASXMASAMAAAAAAAM",
  "SAAAAXMMMSAASMSMSMSXMAMASMMSAAMXASAMSSMSSSXSXMAXAAXAMSMMSMXAMXMAAAXXMMXXMMSXMSAMASAMMSAMXSMAMASMMSSMSXAXMAMAAAMSSXMMMMAAMXAMAMASXMAMXSMSMSMX",
  "ASMSMSXMXMXAXAAAXAMAMAMSXXAXMASXMMXMAAMXAAXMASXMSSMMSMAAXMASMSMMMMMMSXMSSMXSASAMMMAXXMXMSAMMSMSAMXAASMSMSSSSMMXAMXMMAMXMMSMSXSAMXSXMAXAMMMMM",
  "MXMMASMSXMXSMMMMMAMXMSSXAMMXXMAXXASMMSMMAMASXMMAMXMXAMMMMMMMXMASXAXMXAMAAMAXMSAMXXMASMAMXMAMAXXXMMMMXAMXAAXXAXSSSSSMMSAXASASMMASXMAAAMAMAAAX",
  "XAMMAMAAAMAXASXSSXMXXXMAXMXAXXMXSASXAXXXAMXSMMMSMMMSMSXMAXAMSXMMSMSASMMSSMXSXMAMXMMAMMASAXMSXXMAAXXMMMMSMMSSSMAAAXXAASMMSMAMXSSMXSMMMAASXSSS",
  "SXSMAMSSXMAMXMAXXMMSMMSSMMXMXASAMXMMXSXXMMXMASXMAXAXXAXSSSMXAXSXMMSAMSAMXMAMMSMMMXMAXSXSMSXSAMSAMMMSAAAMXXAAAMMMMMMMMMXMMMMMXSXAAXAAXSXSAXAX",
  "MXMXMMAMAXSXMMMMMAXAAMAAAXASXAMXSMSSSMMSSMASXMAAMMSXMMMAXAMMSSMAXAMAMMMSMMMXAAAAAASMXXASAXXMAMXAXASASMMMMMMSMSXXAAXMXMAMSAXSXMMMMSSMXXMMXMAM",
  "SSMMSMASMMMAAAAASMSSSMSSMMASMMMXXAXSAAAAASASXSSXMAXAMXSMMXMAXAMMMMSMMXMAXAAXSSSMSASXSMAMMMXMSMSSMSSMMMSAMXXXXMASMMSAAXMMSXMSAXSMXMAXMAMAMMMM",
  "AAAAXXAMAAXMSSSMSAMAAAXAMXAMASAMMSMMXMMSMMMSAXMAMASAMMAMXSMMSAMXAXAMMSSMSXXMXAAAXAMAXMXMXXXMXAAAXAXXAASASXSMSXXMSASMMMSMMSASAMXMSSSMSAMASASA",
  "SSMMSMMSMMSXMMAMXAMSMMSXXMXSAMASAXXMASXXASAMXMMAMXSMMSAMAXAAMAMMXXASAAAMMMMAMXMSMMMSMMMXXMAMAMMSMSAMAMMAMAXAXMXSMMSAXAAAASMMMMAXXAMASXXXSASX",
  "XAASAMMAMSMXSSMMSAMXXMAMXMAMMSXMXSASXSASAMXSMASXSMSMMSAMASMMSXMASXMMMSSMAAXSXMXAXAAAAXASXMMASXMXXAAXAXXAMXMSMMMXAASXMMSMMSXMAMXSMAMAMMMMMMMM",
  "SMMMASMMMAAAMAMAMASAMMAMXMASMSMSXSXMAMMMMMMAXXAASASAAMAMXMAAXAMXSASAMAXMMSXMASXMASMSXMMSAAMAMAMAMSMMMSSMMXMMAMAMSMSASAAAMXASXSSXXXMAMMASAMAM",
  "AXAMAMAASMSMSAMXSAMAMXSXMXXMXMASAMAMSMAAAMSMSAMXMASMMSMMAMSMSSMAMAMAMXXSAMXSAMAXXMMMMSXSMMMASAMXAAXAAMMSSXMSAMSMXASAMSSMMSMMAXAMAXMMMSMSAXMS",
  "XSXMMSXMMAAXSXSAMXSAMMXAMSMSMMAMAMAMAMSSXMAMMMMXMAMXMAMSXXMAAMMSSMXAMXMMASASXSXMASAAXAAMAMMXMAMMMASMXSAAMXMMASXAXAMAMAMAASAMXMMAXMASASXSXMXM",
  "XMASXMMMMSMMXXMASXMASAMAMAAAXMAMSMSXSXMAMSMXAAXXMXSMSAMAMAMMMSAMAXMAXXMSMMASMSMSMSMMMMMMMXSASMMSXMXMMMMMSMXMMSMMMXMXMASMMSMMAMXSXMXAASAMMSAA",
  "XSSMMMAAMAMMMMMAAASXMMMAMMMMXMAMMAMAMMMAMSXSXSSMMMMASMSAMXSMAMAMAMMMMMMAXMAMXSASXSAMXAAMXMXAAMAMAXAMAAAMAAXMAXAMXSXXMXSMASMXXSMMAXAMMMAMAMAS",
  "XSAMASXSSMMAAAMMMMMAAXSSSSMXMMSAMAMMMSSSMSASAAXMAAMXMASXMAAMASMMSSSXAASASMXXMMAMAXAMSMMXXMMMMMMSMMMSSSSSSSMMXSXMASMMSAMXMMMSAAAXMXXXAMSMMSAX",
  "XMAMXMXMXXSSSSMXAAMXMMMXAXAMXAAMMAMAAMMMAMAMMMMSSMMAMAMAMMMSASAMXAAMSXSXXMMMMMAMMMSMMAAAAMAMXMAAAAXMAAAAAXAXAMAMAXAAMASMSAAAASMAMMSXMMMAMMAM",
  "SSMMASASAMMMAXASMXSAAAXMSMMXMASMSXSMXXAMXMXMAXMAMXSSXXSXMXXMASMMMMMAXMMMAXAAMMSXXXMAXMMMASASAMSXXMMMMMMMMSMMSSMMSSMMSAMXSMSSMAXXXAAMSAMAMMXM",
  "MASXXSASAXAMXMMXAASMSMMAMAMAMAXAXASXXMAMXXXXXMMAXMMXAXSXSAXMASAMSSXMMAAASMSXSAMSAMSSMSSMXXASXMMMSSMXSXXAXAASAMXAAAAXMMSAXXAAMAMSMXSASASASMSM",
  "SAMXMMXMASXSMSXMSMXXXMXXXAMAMMXSMMMAMSSMMSSXSXSMSAAMXMMASMMMMSMMAAAXSMMXXXAAMAMAXMAMMAAMMMMMXMAAAAMAXMXMSSSMXSMMSSSMMMMMSMSSMMXSAAMMSAMASAXS",
  "MXMAASXMXMXAASMMMSSMMAASXSXMSAAXASMXMAAAAXXASAMAXMXMAAMAMMAAMMXMMMXMMSXMXMXSSMMMXMASMSXMAAAXASMMSSMSXSAMXXMAXSXMXAMAAXMAXAAMAMAMXMMAMAMAMAMX",
  "SSSSMMAMXMMMMMASAAMAXMMSAMXAMMXSAMXXMXSMMSMMMMMSMMMSSSMAXSSXSAAMXXAMXAXXMMXXMAAXASXMXXXSXSXMXSXAAAXMASXSMSMXMXAXMAMSSSSSMMMMAMASMXXSSMMSSXMM",
  "XMAMASXMMAAXXSAMMSSSMSXMAMMXMXMMMMXMSAMXAMXMAXXAAAAXMXXMMMAAAMMSSSMSMMXSASASMSMSMSAMXMASAMMSMXMMSSMMAMAMAAAASMMMSMMAAAAMMASXXSAXAMXAAAAAXASX",
  "XMASMSAMXSSSXMASAAMAASAMSMAAAXAAAAAAMASMMSASASXSSMSSXAXMASMMMASXAMSAAAASXMASAAXAMXXMAMSMAMAAAAMMXMAMASAMSMSMSAMAAAMMMMMMSASXAMXMSAMSSMMSSXMM",
  "MMXSXSXMAMAMXSSMMSSMMMXMAMSAMXSSSSXSAMXMSSXSXSAAXAXAMMMSASXXASAMXMXSSMXSSMXMMMSMSXASXSXMXMSMSASASXSSXSXMXAMMSXMSSSMSAMXXMASMSMXAXSAAAAXMMXMS",
];

const maxX = puzzleInput[0].length - 1;
const maxY = puzzleInput.length - 1;
const maxDepth = 4;
const directions = 8;

enum Direction {
  UP = 1,
  DOWN,
  LEFT,
  RIGHT,
  UPRIGHT,
  UPLEFT,
  DOWNRIGHT,
  DOWNLEFT,
}

class Coordinate {
  x: number;
  y: number;

  constructor(x: number, y: number) {
    this.x = x;
    this.y = y;
  }

  copy(): Coordinate {
    return new Coordinate(this.x, this.y);
  }

  getLetter(): string {
    return puzzleInput[this.y][this.x];
  }
}

function getExpectedValue(depth: number): string | null {
  // Takes in a current depth and returns the character we are expecting to get at that point
  switch (depth) {
    case 0: {
      return "X";
    }
    case 1: {
      return "M";
    }
    case 2: {
      return "A";
    }
    case 3: {
      return "S";
    }
    default: {
      return null;
    }
  }
}

function getNextCoordinate(
  coord: Coordinate,
  direction: Direction,
): Coordinate | Error {
  let newCoord = coord.copy();

  switch (direction) {
    case Direction.UP: {
      newCoord.y -= 1;
      break;
    }
    case Direction.DOWN: {
      newCoord.y += 1;
      break;
    }
    case Direction.LEFT: {
      newCoord.x -= 1;
      break;
    }
    case Direction.RIGHT: {
      newCoord.x += 1;
      break;
    }
    case Direction.UPRIGHT: {
      newCoord.x += 1;
      newCoord.y -= 1;
      break;
    }
    case Direction.DOWNRIGHT: {
      newCoord.x += 1;
      newCoord.y += 1;
      break;
    }
    case Direction.UPLEFT: {
      newCoord.x -= 1;
      newCoord.y -= 1;
      break;
    }
    case Direction.DOWNLEFT: {
      newCoord.x -= 1;
      newCoord.y += 1;
      break;
    }
    default: {
      return new Error(`Unknown direction ${direction}.`);
    }
  }

  console.log(`Getting next coord: (${newCoord.x}, ${newCoord.y})`);

  if (newCoord.x < 0 || newCoord.x > maxX) {
    return new Error("X coordinate invalid");
  } else if (newCoord.y < 0 || newCoord.y > maxY) {
    return new Error("Y coordinate invalid");
  } else {
    return newCoord;
  }
}

function searchAllDirections(coord: Coordinate): number {
  // Kind of a cheaty helper: we will only ever search all directions at depth 0,
  // so we can initiate searches on all other directions at depth 1. This should
  // only be called once we know the depth 0 character is correct.
  let matches = 0;

  for (var dir = 1; dir <= directions; dir++) {
    const nextCoord = getNextCoordinate(coord, dir);

    if (nextCoord instanceof Error) {
      console.log(`Got error '${nextCoord.message}'.`);
      continue;
    }

    matches += findMatches(nextCoord, 1, dir);
  }

  return matches;
}

// Naive approach: going through every character on every line and DFS-ing them to find a match
function findMatches(
  coord: Coordinate,
  depth: number,
  direction: Direction | null,
): number {
  // Takes in an x,y coordinate to begin our search from, the current depth, and what direction we
  // are searching in (since we must follow the direction we began the search in).
  //
  // Returns how many matches have been found.

  // Error case: We didn't get a valid coordinate
  if (coord == null) {
    return 0;
  }

  const expectedLetter = getExpectedValue(depth);

  console.log(
    `Finding matches at ${coord.x},${coord.y} (letter is '${coord.getLetter()}') at depth ${depth} (looking for ${expectedLetter}) in direction ${direction}.`,
  );

  // Success case: We are at depth 4 and found a valid end character
  if (depth == 3 && coord.getLetter() == expectedLetter) {
    console.log("Got XMAS! Returning 1");
    return 1;
  }

  // Base case: If we do not have a valid letter, exit out. This branch has nothing.
  if (expectedLetter == null || coord.getLetter() !== expectedLetter) {
    return 0;
  }

  // Base case: If we are past our maximum length of 4, we didn't succeed.
  if (depth > maxDepth) {
    return 0;
  }

  // Some error occured, we should never be greater than depth 0 without knowing our direction
  if (depth > 0 && direction == null) {
    console.log("UH OH!");
  }

  // Only bit of branching logic: if we are on depth 0, we need to try every direction. If we are at depth > 0,
  // we already know our direction so we should only do that.
  if (depth > 0) {
    // Base case: If we cannot get the next coordinate, we are on the edge of the board and cannot search further
    const nextCoord = getNextCoordinate(coord, direction);
    if (nextCoord instanceof Error) {
      console.log(`Got error: ${nextCoord.message}`);
      return 0;
    }
    return findMatches(nextCoord, depth + 1, direction);
  } else {
    // Attempt to find matches in every direction
    return searchAllDirections(coord);
  }
}

function solve() {
  let matches = 0;
  for (var y = 0; y <= maxY; y++) {
    for (var x = 0; x <= maxX; x++) {
      const coord = new Coordinate(x, y);

      // Shortcut: If the coordinate isn't "X" it cannot work so skip over it
      if (coord.getLetter() != "X") {
        continue;
      }

      console.log(`Starting new search at (${coord.x}, ${coord.y}).`);
      matches += findMatches(coord, 0, null);
    }
  }
  return matches;
}

console.log(solve());
